config/routes.rb
Rails.application.routes.draw do
  root 'rewards#index', as: :root
  devise_for :accounts

  resource :account, only: [:edit, :update]
  resources :rewards, only: [:index]

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resource :account, only: [:show, :update]
      resource :session, only: [:create, :destroy]
      resources :rewards, only: [:index]
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :rewards, dependent: :destroy
  has_many :sessions, dependent: :destroy

  validates :name, presence: true

  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reward.rb
class Reward < ApplicationRecord
  enum status: %i[
    waiting_to_be_approved approved 
    denied sent redeemed completed
  ]

  belongs_to :account

  validates :status, presence: true

  scope :status, -> (status) { where(status: status) if status }
end

app/models/session.rb
class Session < ApplicationRecord
  SESSION_LIFE_TIME = 1.month
  enum device_platform: %i[web]
  
  belongs_to :account
  
  validates :device_platform, presence: true

  after_create :destroy_previous_device_sessions, if: -> { device_token }
  
  has_secure_token :access_token

  scope :not_expired, -> { where('updated_at > ?', Time.current - SESSION_LIFE_TIME) }
  
  private

  def destroy_previous_device_sessions
    Session.where.not(id: id).where(device_token: device_token).destroy_all
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @rewards = current_account.rewards.status(filter_params).page(params[:page])
  end

  private

  def filter_params
    Reward.statuses[@filter = params.permit(:filter)[:filter]]
  end
end

app/controllers/api/v1/accounts_controller.rb
class Api::V1::AccountsController < Api::V1::BaseController
  before_action :set_account

  def show; end;

  def update
    if current_account.update_with_password(account_params)
      render :show
    else
      render_error(422, 'NotValid', current_account.errors.full_messages.join(', '))
    end
  end

  private

  def account_params
    params.require(:account).permit(
      :email,
      :name,
      :password,
      :current_password,
      :password_confirmation
    )
  end

  def set_account
    @account = current_account
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found
  rescue_from ActionController::ParameterMissing, with: :render_parameter_missing

  before_action :current_account

  respond_to :json

  def current_account
    @current_account ||= current_session.try(:account)
  end

  def current_session
    @current_session ||= get_session
  end

  def get_session
    session = Session.not_expired.find_by(access_token: request.headers['Access-Token'])
    render_unauthorized unless session

    set_access_token_to_header(session) if session.touch
    session
  end

  def set_access_token_to_header(session)
    response.headers['Access-Token'] = session.access_token
  end

  def render_not_found(e)
    render_error(404, 'NotFound', e.message)
  end

  def render_parameter_missing(e)
    render_error(422, 'ParameterMissing', e.message)
  end

  def render_unauthorized
    render_error(401, 'Unauthorized', 'Invalid access-token')
  end

  def render_error(status, type, message)
    json = { type: type, message: message }
    render json: json, status: status
  end

  def render_success(message)
    json = { message: message }
    render json: json, status: 200
  end
end

app/controllers/api/v1/rewards_controller.rb
class Api::V1::RewardsController < Api::V1::BaseController
  def index
    @rewards = current_account.rewards.status(filter_params).page(params[:page])
  end

  private

  def filter_params
    Reward.statuses[@filter = params.permit(:filter)[:filter]]
  end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::V1::BaseController
  skip_before_action :current_account

  def create
    authentication = ::ApiAuthentications::Email.new(authentication_params)
    if authentication.authenticate
      set_current_session(authentication)
      render 'api/v1/accounts/show'
    else
      render_error(422, 'NotValid', authentication.errors.join(', '))
    end
  end

  def destroy
    current_session.destroy
    render_success('You have successfully signed out')
  end

  private

  def set_current_session(authentication)
    @current_session = authentication.session
    @account = authentication.account
    set_access_token_to_header (@current_session) 
  end

  def authentication_params
    {
      account: account_params,
      session: session_params
    }
  end

  def account_params
    params.require(:account).permit(
      :email,
      :password,
      :name
    )
  end

  def session_params
    params.require(:session).permit(
      :device_platform,
      :device_token
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_account!
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards = current_account.rewards.status(filter_params).page(params[:page])
  end

  private

  def filter_params
    Reward.statuses[@filter = params.permit(:filter)[:filter]]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH_MSG = {
    success: 'alert-success',
    error: 'alert-warning',
    alert: 'alert-danger',
    notice: 'alert-info'
  }

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{BOOTSTRAP_FLASH_MSG[msg_type.to_sym]} fade in") do 
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message 
      end)
    end
    nil
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
  def rewards_options
    Reward.statuses.keys.to_a
  end
end

app/views/accounts/edit.html.erb
<% provide(:button_text, 'Save changes') %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>Update your account</h2>

    <%= form_for(current_account, url: account_path) do |f| %>
      <%= flash_messages %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= f.label :current_password %>
          <%= f.password_field :current_password, class: 'form-control', required: true %>
        </div>
        <div class="panel-body">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
          <br>
          <%= f.submit yield(:button_text), class: "btn btn-primary" %>        
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Donut", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Rewards", root_path %>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if account_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account (<%= current_account.email %>)<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Account settings", edit_account_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_account_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign In", new_account_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlueboardTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rewards/_reward.html.erb
<tr>
  <th scope="row"><%= reward.id %></th>
  <td><%= reward.status %></td>
  <td><%= reward.created_at.strftime('%x %X') %></td>
</tr>

app/views/rewards/index.html.erb
<%= flash_messages %>

<%= form_tag rewards_path, method: :get do %>
  <div class="input-group">
    <%= select_tag(:filter, options_for_select(rewards_options, @filter), include_blank: true, class: "form-control status-selector") %>
  </div>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Status</th>
      <th scope="col">Created at</th>
    </tr>
  </thead>
  <tbody>
    <%= render @rewards %>
  </tbody>
</table>

<%= paginate @rewards %>